/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.softtech.traductorbraille.GUI;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Jodual
 */
public class BrailleCell extends javax.swing.JPanel {

    private boolean[] points = new boolean[6];

    public BrailleCell() {
        setSize(100, 150);
        setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }

    public boolean getPoint(int index) {
        return points[index];
    }

    public void setPoint(int index, boolean value) {
        points[index] = value;
        repaint();
    }

    public void clearPoints() {
        for (int i = 0; i < points.length; i++) {
            points[i] = false;
        }
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(Color.BLACK);
        int cellWidth = getWidth() / 2; // Dividir el ancho del panel en dos partes iguales
        int cellHeight = getHeight() / 3; // Dividir la altura del panel en tres partes iguales

        for (int i = 0; i < 6; i++) {
            int x = (i % 2) * cellWidth + cellWidth / 4; // Centrar el círculo horizontalmente
            int y = (i / 2) * cellHeight + cellHeight / 4; // Centrar el círculo verticalmente
            if (points[i]) {
                g.fillOval(x, y, cellWidth / 2, cellHeight / 2); // Ajustar el tamaño del círculo al tamaño de la celda
            } else {
                g.drawOval(x, y, cellWidth / 2, cellHeight / 2); // Ajustar el tamaño del círculo al tamaño de la celda
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
